[versions]
kotlin = "2.3.0"
compose-multiplatform = "1.10.0"
hot-reload = "1.0.0"
osdetector = "1.7.3"
junit = "4.13.2"
androidx-lifecycle = "2.9.0"
kotlinx-coroutines = "1.10.1"
devsrsouza-compose-icons = "1.1.1"
zutil = "2.0.0-beta3"
commons-compress = "1.26.1"

[libraries]
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-components-uiToolingPreview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "compose-multiplatform" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
icons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "devsrsouza-compose-icons" }
icons-simple = { module = "br.com.devsrsouza.compose.icons:simple-icons", version.ref = "devsrsouza-compose-icons" }
zutil-all = { module = "top.csaf:zutil-all", version.ref = "zutil" }
zutil-awt = { module = "top.csaf:zutil-awt", version.ref = "zutil" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }

[plugins]
# Kotlin Multiplatform：跨平台
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
# Compose 编译器插件
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Compose Multiplatform：UI 框架
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
# Compose Hot Reload：Compose 热部署 https://github.com/JetBrains/compose-hot-reload?tab=readme-ov-file#apply-the-gradle-plugin-to-your-project
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hot-reload" }
# OS Detector：检测系统名称和架构 https://github.com/google/osdetector-gradle-plugin
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
